// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "00dc4d06-af9e-4250-89c3-b187006037d0");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1669381699);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1669381678);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1669381671);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1669381819);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1669381729);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 9569);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1669381669);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5c755aa9-1be1-4856-871e-c9b71728df62}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1669381704780");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1669383477780");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1669381678824");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1669403278824");
user_pref("browser.search.region", "LB");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1669381670");
user_pref("browser.slowStartup.averageTime", 1420);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200720193547");
user_pref("browser.startup.homepage_override.mstone", "79.0");
user_pref("browser.startup.lastColdStartupCheck", 1669381670);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1669381672719");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "79.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "672a04653bc54d2c822e99b64e98f72b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "79.0");
user_pref("extensions.lastPlatformVersion", "79.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e0183d09-1023-4359-a552-911af5894f60\",\"formautofill@mozilla.org\":\"3850b217-1620-4154-b5c1-8b640d7b606e\",\"screenshots@mozilla.org\":\"f1dc4ae7-34ef-4052-bd9a-f502fe544786\",\"webcompat-reporter@mozilla.org\":\"1a1903f7-c6fa-4b57-9c63-24f28bfedbd4\",\"webcompat@mozilla.org\":\"9a499cc3-ca31-44a9-801d-e06eecc2e49e\",\"default-theme@mozilla.org\":\"a3cc90cc-1c44-4b02-b8c0-492bd96d18ac\",\"google@search.mozilla.org\":\"6ebc8fd3-10a6-40a8-8beb-4d122ece3a7f\",\"amazondotcom@search.mozilla.org\":\"6027fd9b-7ef8-4943-ae56-097bdd3f4028\",\"wikipedia@search.mozilla.org\":\"2cb0cd15-e9d4-4e85-b9be-ed3b1722fcb4\",\"bing@search.mozilla.org\":\"70668dd1-f54d-4c79-ab51-8ac78f549f5d\",\"ddg@search.mozilla.org\":\"4cef2728-93c7-45ee-85f8-b7d1cdcffc47\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1669381768);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.2");
user_pref("media.gmp-manager.buildID", "20200720193547");
user_pref("media.gmp-manager.lastCheck", 1669381766);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1669381764);
user_pref("security.remote_settings.intermediates.checked", 1669381764);
user_pref("security.sandbox.content.tempDirSuffix", "df722dc1-8c4e-4032-9475-09b5ffa9698e");
user_pref("security.sandbox.plugin.tempDirSuffix", "0945d717-2999-4d11-9c25-9710ff900192");
user_pref("services.blocklist.addons.checked", 1669381764);
user_pref("services.blocklist.gfx.checked", 1669381764);
user_pref("services.blocklist.plugins.checked", 1669381764);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1669371719839\"");
user_pref("services.settings.last_update_seconds", 1669381764);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1669381764);
user_pref("services.settings.main.cfr.last_check", 1669381764);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1669381764);
user_pref("services.settings.main.hijack-blocklists.last_check", 1669381764);
user_pref("services.settings.main.language-dictionaries.last_check", 1669381764);
user_pref("services.settings.main.message-groups.last_check", 1669381764);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1669381764);
user_pref("services.settings.main.pioneer-study-addons.last_check", 1669381764);
user_pref("services.settings.main.public-suffix-list.last_check", 1669381764);
user_pref("services.settings.main.search-config.last_check", 1669381764);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1669381764);
user_pref("services.settings.main.sites-classification.last_check", 1669381764);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1669381764);
user_pref("services.settings.main.whats-new-panel.last_check", 1669381764);
user_pref("services.settings.security.onecrl.checked", 1669381764);
user_pref("toolkit.startup.last_success", 1669381668);
user_pref("toolkit.telemetry.cachedClientID", "a7d9b176-7b2b-4cb4-9704-531347570694");
user_pref("toolkit.telemetry.pioneer-new-studies-available", true);
user_pref("toolkit.telemetry.previousBuildID", "20200720193547");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
